In [1]:
#Import the required Libraries.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Data Cleaning

### Data Reading & Data Types

In [8]:
#Read the data in pandas
inp0= pd.read_csv("Attribute+DataSet.csv")
inp1= pd.read_csv("Dress+Sales.csv")
inp0.head(10)
#print('\n')
#inp1.head(10)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,chiffonfabric,chiffon,bow,dot,0
5,1068332458,bohemian,Low,0.0,M,Summer,v-neck,sleevless,NaN,NaN,NaN,print,0
6,1220707172,Casual,Average,0.0,XL,Summer,o-neck,full,cotton,NaN,NaN,solid,0
7,1113094204,Flare,Average,0.0,free,Spring,v-neck,short,cotton,broadcloth,beading,solid,1
8,985292672,bohemian,Low,0.0,free,Summer,v-neck,sleevless,nylon,chiffon,NaN,NaN,1
9,1117293701,party,Average,5.0,free,Summer,o-neck,full,polyster,broadcloth,lace,solid,0

You have “Attribute DataSet” which contains a column named “Price”. Choose the correct statement from the following about its data type and variable type.
- Integer type and numerical variable
- Object type and categorical ordinal variable
- Object type and categorical nominal variable
- Float type and categorical variable.

There is another column in “Attribute DataSet” named as “Recommendation”, choose the correct statement about its data type and variable type.
- Integer type and categorical
- Object type and categorical
- Integer type and continuous numerical
- Object type only.

Which of the following column do you think are of no use in “Attribute DataSet”.
- Dress_ID
- Price
- Size and material
- NeckLine
- None of the above

In [9]:
# Print the information about the attributes of inp0 and inp1.
inp0.info()
inp1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 479 entries, 0 to 478
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Dress_ID        479 non-null    int64
 1   Style           479 non-null    object
 2   Price           477 non-null    object
 3   Rating          479 non-null    float64
 4   Size            479 non-null    object
 5   Season          477 non-null    object
 6   NeckLine        476 non-null    object
 7   SleeveLength    477 non-null    object
 8   Material        360 non-null    object
 9   FabricType      223 non-null    object
 10  Decoration      255 non-null    object
 11  Pattern Type    377 non-null    object
 12  Recommendation  479 non-null    int64
dtypes: float64(1), int64(2), object(10)
memory usage: 48.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 479 entries, 0 to 478
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Dress_ID    479 non-null    float64
 1   29-08-2013  479 non-null    int64
 2   31-08-2013  479 non-null    int64
 3   09-02-2013  479 non-null    int64
 4   09-04-2013  479 non-null    int64
 5   09-06-2013  479 non-null    int64
 6   09-08-2013  479 non-null    int64
 7   09-10-2013  479 non-null    int64
 8   09-12-2013  479 non-null    object
 9   14-09-2013  479 non-null    object
 10  16-09-2013  479 non-null    object
 11  18-09-2013  479 non-null    object
 12  20-09-2013  479 non-null    object
 13  22-09-2013  479 non-null    object
 14  24-09-2013  479 non-null    int64
 15  26-09-2013  257 non-null    float64
 16  28-09-2013  479 non-null    int64
 17  30-09-2013  222 non-null    float64
 18  10-02-2013  220 non-null    float64
 19  10-04-2013  221 non-null    float64
 20  10-06-2013  479 non-null    int64
 21  10-08-2013  224 non-null    float64
 22  10-10-2013  224 non-null    float64
 23  10-12-2013  479 non-null    int64
dtypes: float64(7), int64(11), object(6)
memory usage: 89.9+ KB

### Fixing the Rows and Columns

As you can see, there is a column in “Attribute Dataset” named as ‘Size’. This column contains the values in abbreviation format. Write a code in Python to convert the followings:

- M into  “Medium”
- L into  “Large”
- XL into “Extra large”
- free into “Free”
- S, s & small into “Small”.

Now once you are done with changes in the dataset, what is the value of the lowest percentage, the highest percentage and the percentage of Small size categories in the column named “Size”?

In [10]:
# Column fixing, correcting size abbreviation. count the percentage of each size category in "Size" column.
#inp0.Size = inp0.Size.apply(lambda x :"Medium" if x == 'M'else("Large" if x == 'L' else("Extra Large" if x == 'xl' else("Small" if x == 'small' else("Small" if x =='S' else "Free")))))
inp0.Size.replace({'M':"Medium",'L': "Large",'XL':"Extra Large", "free": "Free",'s':"Small", 'small': "Small", 'S':"Small"}, inplace = True)
inp0.head(10)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,Medium,Summer,o-neck,sleevless,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,Large,Summer,o-neck,Petal,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,Large,Automn,o-neck,full,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,Large,Spring,o-neck,full,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,Medium,Summer,o-neck,butterfly,chiffonfabric,chiffon,bow,dot,0
5,1068332458,bohemian,Low,0.0,Medium,Summer,v-neck,sleevless,NaN,NaN,NaN,print,0
6,1220707172,Casual,Average,0.0,Extra Large,Summer,o-neck,full,cotton,NaN,NaN,solid,0
7,1113094204,Flare,Average,0.0,Free,Spring,v-neck,short,cotton,broadcloth,beading,solid,1
8,985292672,bohemian,Low,0.0,Free,Summer,v-neck,sleevless,nylon,chiffon,NaN,NaN,1
9,1117293701,party,Average,5.0,Free,Summer,o-neck,full,polyster,broadcloth,lace,solid,0

In [11]:
# Print the value counts of each category in "Size" column.
inp0.Size.value_counts()

Medium         171
Free           165
Large           93
Small           36
Extra Large     14
Name: Size, dtype: int64

In [12]:
#Print the value counts of each category in "Size" column in %.
inp0.Size.value_counts(normalize=True)*100

Medium         35.699374
Free           34.446764
Large          19.415449
Small           7.515658
Extra Large     2.922756
Name: Size, dtype: float64

### Impute/Remove Missing values

In [13]:
# Print the null count of each variables of inp0 and inp1.
print(inp0.isnull().sum())
print('\n')
print(inp0.shape)
print('\n')
print(inp1.isnull().sum())
print(inp1.shape)

Dress_ID            0
Style               0
Price               2
Rating              0
Size                0
Season              2
NeckLine            3
SleeveLength        2
Material          119
FabricType        256
Decoration        224
Pattern Type      102
Recommendation      0
dtype: int64


(479, 13)


Dress_ID        0
29-08-2013      0
31-08-2013      0
09-02-2013      0
09-04-2013      0
09-06-2013      0
09-08-2013      0
09-10-2013      0
09-12-2013      0
14-09-2013      0
16-09-2013      0
18-09-2013      0
20-09-2013      0
22-09-2013      0
24-09-2013      0
26-09-2013    222
28-09-2013      0
30-09-2013    257
10-02-2013    259
10-04-2013    258
10-06-2013      0
10-08-2013    255
10-10-2013    255
10-12-2013      0
dtype: int64
(479, 24)

You are given another dataset named “Dress Sales”. Now if you observe the datatypes of the columns using ‘inp1.info()’ command, you can identify that there are certain columns defined as object data type though they primarily consist of numeric data.

Now if you try and convert these object data type columns into numeric data type(float), you will come across an error message. Try to correct this error.

In [14]:
# Print the data types information of inp1 i.e. "Dress Sales" data.
inp1.info()
inp1.head(10)
#inp1.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 479 entries, 0 to 478
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Dress_ID    479 non-null    float64
 1   29-08-2013  479 non-null    int64
 2   31-08-2013  479 non-null    int64
 3   09-02-2013  479 non-null    int64
 4   09-04-2013  479 non-null    int64
 5   09-06-2013  479 non-null    int64
 6   09-08-2013  479 non-null    int64
 7   09-10-2013  479 non-null    int64
 8   09-12-2013  479 non-null    object
 9   14-09-2013  479 non-null    object
 10  16-09-2013  479 non-null    object
 11  18-09-2013  479 non-null    object
 12  20-09-2013  479 non-null    object
 13  22-09-2013  479 non-null    object
 14  24-09-2013  479 non-null    int64
 15  26-09-2013  257 non-null    float64
 16  28-09-2013  479 non-null    int64
 17  30-09-2013  222 non-null    float64
 18  10-02-2013  220 non-null    float64
 19  10-04-2013  221 non-null    float64
 20  10-06-2013  479 non-null    int64
 21  10-08-2013  224 non-null    float64
 22  10-10-2013  224 non-null    float64
 23  10-12-2013  479 non-null    int64
dtypes: float64(7), int64(11), object(6)
memory usage: 89.9+ KB

,Dress_ID,29-08-2013,31-08-2013,09-02-2013,09-04-2013,09-06-2013,09-08-2013,09-10-2013,09-12-2013,14-09-2013,...,24-09-2013,26-09-2013,28-09-2013,30-09-2013,10-02-2013,10-04-2013,10-06-2013,10-08-2013,10-10-2013,10-12-2013
0,1.006033e+09,2114,2274,2491,2660,2727,2887,2930,3119,3204,...,3554,3624.0,3706,3746.0,3795.0,3832.0,3897,3923.0,3985.0,4048
1,1.212192e+09,151,275,570,750,813,1066,1164,1558,1756,...,2710,2942.0,3258,3354.0,3475.0,3654.0,3911,4024.0,4125.0,4277
2,1.190381e+09,6,7,7,7,8,8,9,10,10,...,11,11.0,11,11.0,11.0,11.0,11,11.0,11.0,11
3,9.660060e+08,1005,1128,1326,1455,1507,1621,1637,1723,1746,...,1878,1892.0,1914,1924.0,1929.0,1941.0,1952,1955.0,1959.0,1963
4,8.763395e+08,996,1175,1304,1396,1432,1559,1570,1638,1655,...,2032,2156.0,2252,2312.0,2387.0,2459.0,2544,2614.0,2693.0,2736
5,1.068332e+09,4,5,11,13,13,13,16,18,19,...,25,25.0,26,26.0,26.0,26.0,27,27.0,27.0,27
6,1.220707e+09,45,61,131,165,176,209,216,251,262,...,379,400.0,417,424.0,445.0,462.0,474,494.0,503.0,552
7,1.219677e+09,4,13,55,73,76,89,94,117,121,...,160,165.0,169,172.0,196.0,212.0,224,241.0,252.0,263
8,1.113094e+09,5,6,10,12,13,15,16,17,17,...,27,28.0,29,29.0,29.0,29.0,29,29.0,29.0,33
9,9.852927e+08,9,11,12,12,12,12,12,13,13,...,14,14.0,14,14.0,14.0,14.0,14,14.0,14.0,14

In [34]:
#dropping the missing (Material column)value 
print(inp0.isnull().sum())
print(inp0.shape)
print ('\n')
inp2=inp0[~inp0.Material.isnull()].copy()
print ('\n')
print(inp2.isnull().sum())
print(inp2.shape)

Dress_ID            0
Style               0
Price               2
Rating              0
Size                0
Season              2
NeckLine            3
SleeveLength        2
Material          119
FabricType        256
Decoration        224
Pattern Type      102
Recommendation      0
dtype: int64
(479, 13)




Dress_ID            0
Style               0
Price               0
Rating              0
Size                0
Season              1
NeckLine            2
SleeveLength        2
Material            0
FabricType        184
Decoration        157
Pattern Type       53
Recommendation      0
dtype: int64
(360, 13)

In [37]:
# Try to convert the object type into float type of data.
inp1['18-09-2013'][inp1['18-09-2013']=='Removed']

Series([], Name: 18-09-2013, dtype: object)

In [31]:
# Do the required changes in the "Dress Sales" data set to get null values on string values.
inp1.loc[inp1['18-09-2013']== 'removed',"18-09-2013"] = np.NaN
inp1.loc[inp1['09-12-2013']== 'removed',"09-12-2013"] = np.NaN
inp1.loc[inp1['14-09-2013']== 'removed',"14-09-2013"] = np.NaN
inp1.loc[inp1['16-09-2013']== 'removed',"16-09-2013"] = np.NaN
inp1.loc[inp1['20-09-2013']== 'removed',"20-12-2013"] = np.NaN
inp1.loc[inp1['22-09-2013']== 'removed',"22-12-2013"] = np.NaN

In [32]:
# Convert the object type columns in "Dress Sales" into float type of data type.
#print(inp0['Style'].dtypes)
print(inp1['09-12-2013'].dtypes)
inp1['09-12-2013'] = inp1['09-12-2013'].astype(float)
inp1['18-09-2013'] = inp1['18-09-2013'].astype(float)

#inp1.info()

object

ValueError: could not convert string to float: 'Removed'

When you see the null counts in “Dress Sales” dataset after performing all the operations that have been mentioned in jupyter notebook, you will find that there are some columns in “Dress Sales” data where there are more than 40% of missing values. Based on your understanding of dealing with missing values do the following steps.

In [36]:
# Print the null percetange of each column of inp1.
inp1.isnull().sum()*100/len(inp1)

Dress_ID        0.000000
29-08-2013      0.000000
31-08-2013      0.000000
09-02-2013      0.000000
09-04-2013      0.000000
09-06-2013      0.000000
09-08-2013      0.000000
09-10-2013      0.000000
09-12-2013      0.000000
14-09-2013      0.208768
16-09-2013      0.208768
18-09-2013      0.208768
20-09-2013      0.000000
22-09-2013      0.000000
24-09-2013      0.000000
26-09-2013     46.346555
28-09-2013      0.000000
30-09-2013     53.653445
10-02-2013     54.070981
10-04-2013     53.862213
10-06-2013      0.000000
10-08-2013     53.235908
10-10-2013     53.235908
10-12-2013      0.000000
20-12-2013    100.000000
22-12-2013    100.000000
dtype: float64

In [15]:
#### Drop the columns in "Dress Sales" which have more than 40% of missing values.
(inp1.isnull().sum()/len(inp1)*100>40.0)[:]

Dress_ID      False
29-08-2013    False
31-08-2013    False
09-02-2013    False
09-04-2013    False
09-06-2013    False
09-08-2013    False
09-10-2013    False
09-12-2013    False
14-09-2013    False
16-09-2013    False
18-09-2013    False
20-09-2013    False
22-09-2013    False
24-09-2013    False
26-09-2013     True
28-09-2013    False
30-09-2013     True
10-02-2013     True
10-04-2013     True
10-06-2013    False
10-08-2013     True
10-10-2013     True
10-12-2013    False
dtype: bool

You should categorise the dates into seasons in “Dress Sales” data to simplify the analysis according to the following criteria:
- June, July and August: Summer.
- September, October and November: Autumn.
- December, January and February: WInter.
- March, April and May: Spring.

In [42]:
# Create the four seasons columns in inp1, according to the above criteria.
Spring = (inp1['09-04-2013'].sum()).sum()
Winter = (inp1[['09-02-2013','10-12-2013']].sum()).sum()
print(Spring)
print(Winter)

143600
314990

In [44]:
# calculate the sum of sales in each seasons in inp1 i.e. "Dress Sales".
inp1['Spring'] = inp1.apply(lambda x: x['09-04-2013'], axis=1)
inp1['Winter'] = inp1.apply(lambda x: x['09-02-2013'] + x['09-12-2013']+ x['10-12-2013'], axis=1)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

Now let's merge inp1 with inp0 with left join manner, so that the information of inp0 should remain intact.

In [26]:
# Merge inp0 with inp1 into inp0. this is also called left merge.
inp0 = pd.merge(left=inp0,right=inp1, how='left', left_on='Dress_ID', right_on='Dress_ID')
inp0.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,Material,FabricType,...,24-09-2013_y,26-09-2013_y,28-09-2013_y,30-09-2013_y,10-02-2013_y,10-04-2013_y,10-06-2013_y,10-08-2013_y,10-10-2013_y,10-12-2013_y
0,1006032852,Sexy,Low,4.6,Medium,Summer,o-neck,sleeveless,NaN,chiffon,...,3554,3624.0,3706,3746.0,3795.0,3832.0,3897,3923.0,3985.0,4048
1,1212192089,Casual,Low,0.0,Large,Summer,o-neck,Petal,microfiber,NaN,...,2710,2942.0,3258,3354.0,3475.0,3654.0,3911,4024.0,4125.0,4277
2,1190380701,vintage,High,0.0,Large,Autumn,o-neck,full,polyster,NaN,...,11,11.0,11,11.0,11.0,11.0,11,11.0,11.0,11
3,966005983,Brief,Average,4.6,Large,Spring,o-neck,full,silk,chiffon,...,1878,1892.0,1914,1924.0,1929.0,1941.0,1952,1955.0,1959.0,1963
4,876339541,cute,Low,4.5,Medium,Summer,o-neck,butterfly,chiffonfabric,chiffon,...,2032,2156.0,2252,2312.0,2387.0,2459.0,2544,2614.0,2693.0,2736

In [ ]:
# Now Drop the Date columns from inp0 as it is already combined into four seasons.
inp0.drop(inp0.loc[:,'29-08-2013':'10-12-2013'].columns, axis= 1, inplace= True)
inp0.isnull().sum()

Print the null count of inp0 to get the idea about the missing values in data set.

In [ ]:
# Print the null count of each columns in inp0 dataframe i.e. combined data frame of inp0 and inp1 without date columns.

You can see that there are two types of variables one with a large number of missing values and another is very less number of missing values. These two columns can be categorized as:

Type-1: Missing values are very less (around 2 or 3 missing values): Price, Season, NeckLine, SleeveLength, Winter and Autumn. 

Type-2: Missing values are large in numbers (more than 15%): Material, FabricType, Decoration and Pattern Type.

In [ ]:
# Deal with the missing values of Type-1 columns: Price, Season, NeckLine, SleeveLength, Winter and Autumn.

In [ ]:
# Deal with the missing values for Type-2 columns: Material, FabricType, Decoration and Pattern Type.

### Standardise value

In the given dataset, there are certain discrepancies with the categorical names such as irregular spellings. Choose the correct option of columns with irregular categories and update them.
 
- Season, NeckLine
- Price, Material
- fabricType, Decoration
- Season, SleeveLength

In [12]:
#correcting the Spellings for column Season
inp0.Season.value_counts()

Summer    154
Spring    116
Winter     94
Automn     59
winter     45
Autumn      7
spring      2
Name: Season, dtype: int64

In [14]:
inp0.Season.replace({'winter': "Winter",'Automn':"Autumn", "spring": "Spring"}, inplace = True)
inp0.head(10)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,Medium,Summer,o-neck,sleevless,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,Large,Summer,o-neck,Petal,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,Large,Autumn,o-neck,full,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,Large,Spring,o-neck,full,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,Medium,Summer,o-neck,butterfly,chiffonfabric,chiffon,bow,dot,0
5,1068332458,bohemian,Low,0.0,Medium,Summer,v-neck,sleevless,NaN,NaN,NaN,print,0
6,1220707172,Casual,Average,0.0,Extra Large,Summer,o-neck,full,cotton,NaN,NaN,solid,0
7,1113094204,Flare,Average,0.0,Free,Spring,v-neck,short,cotton,broadcloth,beading,solid,1
8,985292672,bohemian,Low,0.0,Free,Summer,v-neck,sleevless,nylon,chiffon,NaN,NaN,1
9,1117293701,party,Average,5.0,Free,Summer,o-neck,full,polyster,broadcloth,lace,solid,0

In [16]:
##correcting the Spellings for column NeckLine
inp0.NeckLine.value_counts()

o-neck             257
v-neck             119
slash-neck          25
boat-neck           18
Sweetheart          14
turndowncollor      13
bowneck             10
sqare-collor         5
peterpan-collor      5
open                 3
Scoop                2
mandarin-collor      1
ruffled              1
backless             1
halter               1
sweetheart           1
Name: NeckLine, dtype: int64

In [18]:
inp0.NeckLine.replace({'sweetheart': "Sweetheart"}, inplace = True)
inp0.NeckLine.value_counts()

o-neck             257
v-neck             119
slash-neck          25
boat-neck           18
Sweetheart          15
turndowncollor      13
bowneck             10
sqare-collor         5
peterpan-collor      5
open                 3
Scoop                2
halter               1
ruffled              1
backless             1
mandarin-collor      1
Name: NeckLine, dtype: int64

In [24]:
#correcting the Spellings for column Material  & SleeveLength
inp0.Material.replace({'shiffon': "chiffonfabric",'model': "modal", 'sill': "silk"}, inplace = True)
inp0.Material.value_counts()  
inp0.SleeveLength.replace({'sleevless': "sleeveless",'sleeevless': "sleeveless", 'sleveless': "sleeveless",'thressqatar': "threequarter",'threequater': "threequarter",'capsleeves': "cap-sleeves",'urndowncollor': "turndowncollor"}, inplace = True)
inp0.SleeveLength.value_counts()

sleeveless        223
full               94
short              92
halfsleeve         32
threequarter       26
cap-sleeves         5
turndowncollor      2
butterfly           1
Petal               1
half                1
Name: SleeveLength, dtype: int64

## Univariate Analysis

### Categorical Unordered Univariate Analysis

There is a column named ‘Style’ in ‘Attribute Dataset’ which consists of the different style categories of the women apparels. Certain categories whose total sale is less than 50000 across all the seasons is considered under one single category as ‘Others’.

Which of the following categories in ‘Style’ column can be grouped into ‘Others’ category? and perform the grouping operation in the notebook for further analysis.
- Flare, fashion
- Novelty, bohemian
- OL, fashion, work
- Novelty, fashion, Flare

In [87]:
# Group "Style" categories into "Others" which have less than 50000 sales across all the seasons.
inp0.Style.describe()
inp0.head(20)
#inp0.groupby(inp0.Style).sum()[(inp0.groupby(inp0.Style).sum()).TotalSales<50000]

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,Medium,Summer,o-neck,sleevless,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,Large,Summer,o-neck,Petal,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,Large,Automn,o-neck,full,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,Large,Spring,o-neck,full,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,Medium,Summer,o-neck,butterfly,chiffonfabric,chiffon,bow,dot,0
5,1068332458,bohemian,Low,0.0,Medium,Summer,v-neck,sleevless,NaN,NaN,NaN,print,0
6,1220707172,Casual,Average,0.0,Extra Large,Summer,o-neck,full,cotton,NaN,NaN,solid,0
7,1113094204,Flare,Average,0.0,Free,Spring,v-neck,short,cotton,broadcloth,beading,solid,1
8,985292672,bohemian,Low,0.0,Free,Summer,v-neck,sleevless,nylon,chiffon,NaN,NaN,1
9,1117293701,party,Average,5.0,Free,Summer,o-neck,full,polyster,broadcloth,lace,solid,0
10,898481530,Flare,Average,0.0,Free,Spring,v-neck,short,nylon,NaN,NaN,animal,0
11,957723897,sexy,Low,4.7,Medium,Winter,o-neck,threequarter,NaN,chiffon,lace,print,1
12,749031896,vintage,Average,4.8,Medium,Summer,o-neck,short,cotton,jersey,NaN,animal,1
13,1055411544,Casual,Low,5.0,Medium,Summer,boat-neck,short,cotton,NaN,sashes,solid,0
14,1162628131,Casual,Low,0.0,Free,Winter,boat-neck,full,other,other,lace,NaN,0
15,624314841,cute,Average,4.7,Large,spring,o-neck,short,cotton,NaN,sashes,solid,1
16,830467746,bohemian,Medium,5.0,Free,Automn,o-neck,full,NaN,NaN,hollowout,patchwork,1
17,840857118,Brief,Average,0.0,Medium,Winter,peterpan-collor,threequarter,cotton,NaN,NaN,patchwork,0
18,1113221101,Sexy,Average,5.0,Medium,Automn,o-neck,sleevless,milksilk,NaN,NaN,NaN,1
19,861754372,Sexy,Average,4.5,Large,Automn,o-neck,full,cotton,NaN,beading,solid,0

In [98]:
inp0['TotalSales'] = inp0.apply(lambda x: x['Summer'] + x['Winter']+ x['Autumn']+ x['Spring'], axis=1)

KeyError: 'Summer'

What is the percentage of “cute” and “Others” category in “Style” column in “Attribute DataSet” respectively?
- 46%, 5%
- 9%, 2.1%
- 2.1%, 5%
- 13.8%, 9%

In [18]:
# Calculate the percentage of each categories in the "Style" variable.
inp0.Style.value_counts(normalize=True)*100

Casual      45.720251
Sexy        13.778706
party       10.647182
cute         9.185804
vintage      5.219207
bohemian     4.801670
Brief        3.549061
work         3.549061
sexy         1.461378
Novelty      1.252610
Flare        0.417537
fashion      0.208768
OL           0.208768
Name: Style, dtype: float64

Similarly Club Neckline, SLeeve length categories into "Others" which have less than 50000 sales across all the seasons.

In [ ]:
# Group "Neckline" categories into "Others" which have less than 50000 sales across all the seasons.

In [ ]:
# Group "Sleeve length" categories into "Others" which have less than 50000 sales across all the seasons.

Club material, fabrictype, patterntype and decoration categories into "Others" which have less than 25000 sales across all the seasons

In [ ]:
# Group "material" categories into "Others" which have less than 25000 sales across all the seasons.

In [ ]:
# Group "fabric type" categories into "Others" which have less than 25000 sales across all the seasons.

In [ ]:
# Group "patern type" categories into "Others" which have less than 25000 sales across all the seasons.

In [ ]:
# Group "decoration" categories into "Others" which have less than 25000 sales across all the seasons.

### Caregorical Ordered Univariate Analysis

Which of the following is an unordered variable in “Attribute DataSet”.
- Style
- Price
- Season
- Size

### Numerical variable Univariate analysis:

What is the approximate difference between the maximum value and 75th percentile in “Autumn” column.
- Approx 54000
- Approx 55000
- Approx 52000
- Approx 50000

In [32]:
# Describe the numerical variale: "Autumn".
#inp0.Season.value_counts()
inp0.Season.replace({'Automn': "Autumn"}, inplace = True)
inp0.Season.value_counts()
inp0.Season.Autumn.describe()

AttributeError: 'Series' object has no attribute 'Autumn'

In [ ]:
# plot the boxplot of "Autumn" column.

Which of the following season has the highest difference between the maximum value and 99th quantile of sales?
- Winter
- Summer
- Spring
- Autumn

In [ ]:
# Find the maximum and 99th percentile of Winter season.

In [ ]:
# Find the maximum and 99th percentile of Summer season.

In [ ]:
# Find the maximum and 99th percentile of Spring season.

In [ ]:
# Find the maximum and 99th percentile of Autumn season.

## Bivariate Analysis

### Numerical- Categorical analysis

Which of the following “Price” category has the lowest average value of rating?
- very-high
- Medium
- Low
- High

In [20]:
# Find the Mean of Ratings for each Price category.
inp0.groupby('Price')['Rating'].mean()

Price
Average      3.464167
High         2.914286
Low          3.692121
Medium       3.156667
very-high    3.123810
Name: Rating, dtype: float64

What is the median of the rating of “vintage” category in Style column?
- 4.6
- 4.7
- 4.55
- 0.00

In [22]:
# Find the median of Ratings for each Style category.
inp0.groupby('Style')['Rating'].mean()

Style
Brief       4.064706
Casual      3.517808
Flare       0.000000
Novelty     2.350000
OL          0.000000
Sexy        3.319697
bohemian    3.873913
cute        3.270455
fashion     4.000000
party       3.711765
sexy        3.814286
vintage     3.168000
work        3.911765
Name: Rating, dtype: float64

Which of the following season has the highest average value of sale for “Recommendation” value equals to 1.
- Summer
- Spring
- Autumn
- Winter

In [ ]:
# Summer sale vs Recommendation.

In [ ]:
# Spring sale vs Recommendation.

In [ ]:
# Autumn sale vs Recommendation.

In [ ]:
# Winter sale vs Recommendation.

### Categorical categorical bivariate analysis

Which of the following size categories has the highest positive recommendations?
- Medium and extra large
- Extra large and small
- Free and small
- Free and medium

In [ ]:
# Size vs Recommendation.

### Multivariate analysis

Which of the following pair of “Style” and “Price” category has the highest average of positive recommendations?
- Price: medium and style: vintage
- Price: medium and style: cute
- Price: very high and style: party
- Price: low and style: sexy

In [ ]:
# plot the heat map of Style, price and Recommendation.

Which of the following material type has no recommendation in summer and winter seasons?
- Mix and Milksilk
- Nylon and Rayon
- Microfiber and Silk
- Milksilk and Microfiber

In [ ]:
# plot the heat map of Season, material and Recommendation.